### ISSUE TITLE
Print a nice error message when dealing with a docker repo that has never run containers

### ISSUE THREAD

**Issue by paradoxengine** [google/docker-explorer#44] opened 2018-08-01 22:34 UTC
I happened to run into this while targeting a local repo (which had never run any container, just downloaded an image)

$ sudo de.py -r /var/lib/docker list all_containers
Couldn't find any container configuration file ('{0:s}'). Make sure the docker repository ({1:s}) is correct. If it is correct, you might want to run this script with higher privileges.
Traceback (most recent call last):
  File "/usr/local/bin/de.py", line 4, in <module>
    __import__('pkg_resources').run_script('docker-explorer==20180612', 'de.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 304, in <module>    
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 293, in Main    
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 232, in ShowContainers    
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 204, in GetContainersString    
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 179, in GetContainersList    
  File "/usr/local/lib/python2.7/dist-packages/docker_explorer-20180612-py2.7.egg/EGG-INFO/scripts/de.py", line 162, in GetAllContainers
AttributeError: 'NoneType' object has no attribute 'format'

The list repositories command works nicely under these conditions.

**Comment by rgayon** [comment] 2018-09-24 14:18
Could not reproduce, was fixed in #42

**Closed by rgayon** 2018-09-24 14:18 UTC
